</$objtype/mkfile

TARG=\
	test_atomspace\
	test_pln\
	test_ecan\
	test_ure\
	test_machspace\
	test_pattern\
	test_integration\

HFILES=\
	/sys/include/plan9cog.h\
	/sys/include/plan9cog/atomspace.h\
	/sys/include/plan9cog/pln.h\
	/sys/include/plan9cog/cogvm.h\

OFILES=

