</$objtype/mkfile

LIB=libplan9cog.a
OFILES=\
	plan9cog.$O\
	ecan.$O\
	machspace.$O\
	reactor.$O\
	patternmine.$O\
	openpsi.$O\
	temporal.$O\

HFILES=\
	/sys/include/plan9cog.h\
	/sys/include/plan9cog/openpsi.h\
	/sys/include/plan9cog/temporal.h\

